### ISSUE TITLE
cec.init() fails to open with garbage error message.

### ISSUE THREAD

**Issue by tcumming123** [trainman419/python-cec#16]
On a raspberry pi zero, I get the following error on open. Python-cec was installed using the README.md 0.2.5 recipe (wget... to pip install cec).

cec-client works fine on same pi, tv, etc.

pi@raspberrypi:/tmp $ python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cec
>>> cec.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: CEC failed to open P
                             ����붘����jq
>>>

**Comment by tcumming123** [comment]
More info if this helps:

libCEC version: 3.0.1,  compiled on Fri Jul  3 19:20:43 UTC 2015 by pbuilder@mgorven-pc.thefacebook.com on Linux 3.16.0-41-generic (armv7l), features: P8_USB, P8_detect, 'RPi'
*** Error in `cec-client': corrupted double-linked list: 0x0195c540 ***

**Comment by tcumming123** [comment]
Forgot to mention the segfault...

Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cec
>>> cec.list_adapters()
['RPI']
>>> cec.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: CEC failed to open PҾ����!����
>>> cec.list_adapters()
Segmentation fault

**Comment by digisuji** [comment]
tcumming123, I get the same error...did u get to figure out what was wrong?

Thanks.

**Comment by Kiboneu** [comment]
I had a similar problem, though instead of garbage I got a straight segfault on 'log_cb' when running 'cec.init()' (python 3.6, libcec 4.0.2, cec 0.2.6).

I didn't really bother finding the root cause, but I found that building from the repo and replacing 'cec.so' from pip with the git-built version (5a2a6c8) resolved the issue for me.
